// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDR8yfQygGxb_y_7VaqnJrNm42mdMEMkA',
    appId: '1:781608097048:web:dfa50b5f9e5de313cb3a6d',
    messagingSenderId: '781608097048',
    projectId: 'kaengkaeng-final-project',
    authDomain: 'kaengkaeng-final-project.firebaseapp.com',
    storageBucket: 'kaengkaeng-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbCzLHmf6oVeCyajcQymGo3Gyrg28XiE',
    appId: '1:781608097048:android:18a8e45c0a97c8d3cb3a6d',
    messagingSenderId: '781608097048',
    projectId: 'kaengkaeng-final-project',
    storageBucket: 'kaengkaeng-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Qz7uyF-VaWqlX6pGMHv4sXZ2wa90ibQ',
    appId: '1:781608097048:ios:83e429bf40de4dbdcb3a6d',
    messagingSenderId: '781608097048',
    projectId: 'kaengkaeng-final-project',
    storageBucket: 'kaengkaeng-final-project.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
